In [1]:
import pygmt
import numpy as np
import pandas as pd

#pygmt.show_versions()

In [3]:
# Creating a 1D array
arr1d = np.array([1,2,3,4,5])

# Creating a 2D array
arr2d = np.array([[1,2,3],[4,5,6]])

# Creating a 3D array
arr3d = np.array([[[1,2,1],[3,4,1],[5,6,1]],[[5,6,1],[7,8,1],[9,8,1]]])

print(arr1d.shape)
print(arr2d.shape)
print(arr3d.shape)

(5,)
(2, 3)
(2, 3, 3)


In [13]:
print('1D Array')
print(arr1d)
print('2D Array')
print(arr2d)
print('3D Array')
print(arr3d)

1D Array
[1 2 3 4 5]
2D Array
[[1 2 3]
 [4 5 6]]
3D Array
[[[1 2 1]
  [3 4 1]
  [5 6 1]]

 [[5 6 1]
  [7 8 1]
  [9 8 1]]]


In [15]:
print(arr3d.shape)

(2, 3, 3)


In [16]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
result = arr3d * 2
result

array([[[ 2,  4,  2],
        [ 6,  8,  2],
        [10, 12,  2]],

       [[10, 12,  2],
        [14, 16,  2],
        [18, 16,  2]]])

In [ ]:
def get_one_month_hourdata(adata, month):
    '''
    adata is [month, day, hour, value]
    return decimal days and tide values
    '''
    subset_index = np.where(adata[:,0]==int(month))[0]
    

In [ ]:
subset_index = np.where(adata[:,0]==int(month))[0]

In [23]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.where(a<5, a, 10*a)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])