In [1]:
import xarray as xr
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:

array = np.random.randn(5,3)
print(array)
print(array.shape)
print(array.sum(axis=0))  # Sum along the first axis (columns)
print(array.sum(axis=1))  # Sum along the second axis (rows)
print(array.size)




# print("2D Array filled with random values : \n", array);

# print(array.mean(axis=0))  # Mean along the first axis (columns)
# print(array.mean(axis=1))  # Mean along the second axis (rows)
# print(array.mean())        # Mean of the entire array

[[-0.14686093  0.15478455 -0.90948028]
 [-0.44219261  0.18832724  0.08405139]
 [-0.46676455  0.76895056  0.04808092]
 [-1.50256593  0.45582633  0.39640265]
 [-0.90562661  0.52411318  2.98615066]]
(5, 3)
[-3.46401062  2.09200187  2.60520534]
[-0.90155666 -0.16981398  0.35026694 -0.65033695  2.60463723]
15
