In [1]:
import numpy as np

In [60]:
a = np.array([1,2,3])
print(a.dtype)
print(a.shape)

int32
(3,)


In [56]:
print(np.zeros(3))
print(np.ones(3))
print(np.empty(3))
print(np.full(3,7.))

[0. 0. 0.]
[1. 1. 1.]
[1. 1. 1.]
[7. 7. 7.]


In [61]:
print(np.array([1,2,3]))
print(np.zeros_like(a))
print(np.ones_like(a))
print(np.empty_like(a))
print(np.full_like(a,7))

[1 2 3]
[0 0 0]
[1 1 1]
[1 1 1]
[7 7 7]


In [68]:
print(np.arange(6))
print(np.arange(2,6))
np.arange(1,6,2)

[0 1 2 3 4 5]
[2 3 4 5]


array([1, 3, 5])

In [78]:
np.linspace(0,0.5,5)

array([0.   , 0.125, 0.25 , 0.375, 0.5  ])

In [77]:
np.arange(10).astype(float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [79]:
print('Hello')

Hello


In [82]:
num = 3 
if num == 2:
    print('True')
else:
    print('False')

False


In [86]:
fname = 'Ravi '
mname = 'Chandra '
lname =  'Vedula'


my_full_name = fname + \
mname + \
lname 

print(my_full_name)

Ravi Chandra Vedula


In [88]:
days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
print(days)

['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']


In [89]:
word  = 'word'
sentence = "This is a sentence."
pragraph = """" This is a multi line paragraph.  
It is made up of multiple lines and sentences. """

In [98]:

#This is ignored by the intrepreter.

#First Comment. 

print('Learning Python ') #This will also be ignored.

#I can do multiline comment as follows:


Learning Python 


In [99]:
input("\n\nPress the enter key to exit")



Press the enter key to exit


''

In [100]:
input("\n\nPress the enter key to exit")



Press the enter key to exitThekey


'Thekey'