In [5]:
import pygmt
import pandas as pd
import numpy as np
#pygmt.show_versions()

In [40]:
arr0d = np.array(42)
arr1d = np.array([1,2,3,4,5,6])
arr2d = np.array([[1,2],[3,4],[5,6]])
arr3d = np.array([[[1,2],[3,4],[11,12]],[[5,6],[7,8],[9,10]]])

In [41]:
print(arr0d.shape)
print(arr1d.shape)
print(arr2d.shape)
print(arr3d.shape)

print(arr0d.size)
print(arr1d.size)
print(arr2d.size)
print(arr3d.size)

print(arr0d.ndim)
print(arr1d.ndim)
print(arr2d.ndim)
print(arr3d.ndim)

print(type(arr0d))
print(type(arr1d))
print(type(arr2d))
print(type(arr3d))

()
(6,)
(3, 2)
(2, 3, 2)
1
6
6
12
0
1
2
3
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [36]:
arr3d.shape

(2, 3, 2)

In [37]:
print(np.__version__)

1.26.4


In [39]:
samp_ndarray = np.array((1,2,3,4,5))
print(samp_ndarray)

[1 2 3 4 5]


In [89]:
a = np.array([1,2,3,4,5], ndmin = 4)
print(a)
print('number of dimensions:',a.ndim)

[[[[1 2 3 4 5]]]]
number of dimensions: 4


In [60]:
print(arr1d[2]+arr1d[3])

7


In [73]:
print('2nd element on 1st row : ',arr2d.shape, arr2d[1, 1])

2nd element on 1st row :  (3, 2) 4


In [74]:
print('last element of 2nd dim in 2d array', arr2d[0,-1])

last element of 2nd dim in 2d array 2


In [84]:
print(arr1d[::2])

[1 3 5]


In [90]:
np.info(a)

class:  ndarray
shape:  (1, 1, 1, 5)
strides:  (20, 20, 20, 4)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x231377c4ef0
byteorder:  little
byteswap:  False
type: int32


In [93]:
np.info(arr2d)

class:  ndarray
shape:  (3, 2)
strides:  (8, 4)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x231377c4d70
byteorder:  little
byteswap:  False
type: int32


In [104]:
rows = arr3d.shape[0]
rows

2

In [106]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])
print(arr[0:2, 2])

[7 8 9]
[3 8]


In [109]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [111]:
print(arr[4:])
print(arr[:4])

[5 6 7]
[1 2 3 4]


In [113]:
print(arr[-3:])

[5 6 7]


In [116]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [117]:
import numpy as np

arr = np.array([1,2,3,4,5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]
